---
version: 2
updates:
  - package-ecosystem: docker
    target-branch: master
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      Docker:
        patterns:
          - "*"
    assignees:
      - "hspaans"

  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    assignees:
      - "hspaans"
