---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: centos-7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: centos-7

  - package-ecosystem: docker
    target-branch: master
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      Docker:
        patterns:
          - "*"
    assignees:
      - "hspaans"

  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    assignees:
      - "hspaans"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-buster

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-buster

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bullseye

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    target-branch: debian-bullseye

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bookworm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    target-branch: debian-bookworm

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-focal

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    target-branch: ubuntu-focal

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-jammy

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    target-branch: ubuntu-jammy
