---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    groups:
      docker-alpine:
        patterns:
          - "alpine"
        update-types: ["patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
