---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: centos-7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: centos-7

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-buster

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-buster

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bullseye

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bullseye

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bookworm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: debian-bookworm

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-bionic

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-bionic

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-focal

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-focal

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-jammy

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: ubuntu-jammy

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: fedora-34

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: fedora-34

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: fedora-35

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: fedora-35
