---
repository:
  description: Containers for Molecule
  topics: ansible, docker, molecule, molecule-container, molecule-docker, molecule-podman, debian, ubuntu, centos, fedora
  delete_branch_on_merge: true
  has_wiki: false
