---
repository:
  description: Containers for Molecule
  topics: ansible, molecule, molecule-container, molecule-docker, molecule-podman, debian, ubuntu
  delete_branch_on_merge: true
  has_wiki: false