FROM docker.io/alpine:3.21.3

LABEL org.opencontainers.image.description="Alpine container for Molecule"
LABEL org.opencontainers.image.source=https://github.com/hspaans/molecule-containers

# Configure apt and install packages
# hadolint ignore=DL3033
RUN apk --no-cache add python3 \
    # Clean up
    && apk cache clean

CMD ["/sbin/init"]
