FROM docker.io/rockylinux:9.3.20231119

LABEL org.opencontainers.image.description="Rocky Linux 9 container for Molecule"
LABEL org.opencontainers.image.source=https://github.com/hspaans/molecule-containers

# Configure apt and install packages
# hadolint ignore=DL3033
RUN yum -y install systemd systemd-sysv python3 sudo \
    # Clean up
    && yum clean all

# Make sure systemd doesn't start agettys on tty[1-6].
RUN rm -f /lib/systemd/system/multi-user.target.wants/getty.target

VOLUME ["/sys/fs/cgroup"]

CMD ["/lib/systemd/systemd"]