---
name: Container Release (Debian 11)

on:
  push:
    branches:
      - master
    paths:
      - "debian-11/Dockerfile"
      - ".github/workflows/container-release-debian-11.yml"
  workflow_dispatch:

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: debian-11/Dockerfile
          tags: ghcr.io/hspaans/molecule-containers:debian-11
