---
name: Container Release (Ubuntu 24.04)

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile.ubuntu-24.04'
      - '.github/workflows/container-release-ubuntu-24.04.yml'

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          file: Dockerfile.ubuntu-24.04
          tags: |
            ghcr.io/hspaans/molecule-container-ubuntu:24.04
            ghcr.io/hspaans/molecule-container-ubuntu:noble
            ghcr.io/hspaans/molecule-container-ubuntu:devel
