---
name: Container Release (Fedora 38)

on:
  push:
    branches:
      - master
    paths:
      - "Dockerfile.fedora-38"
      - ".github/workflows/container-release-fedora-38.yml"
  pull_request:
    branches:
      - master
    paths:
      - "Dockerfile.fedora-38"
      - ".github/workflows/container-release-fedora-38.yml"

jobs:
  build-test:
    name: Container Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run tests
        run: docker build . --file Dockerfile.fedora-38

  build-release:
    name: Container Release
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.fedora-38
          tags: ghcr.io/hspaans/molecule-containers:fedora-38
